{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5b6a998b-8ebd-437b-9429-033146ca470c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total CSV Files: 6863\n",
      "\n",
      "==================================================\n",
      "File: Axis_Bluechip.csv\n",
      "Shape: (3581, 2)\n",
      "\n",
      "Columns:\n",
      "Index(['date', 'nav'], dtype='str')\n",
      "\n",
      "Missing Values:\n",
      "date    0\n",
      "nav     0\n",
      "dtype: int64\n",
      "\n",
      "Duplicates:\n",
      "0\n",
      "\n",
      "==================================================\n",
      "File: data_2006_04_01.csv\n",
      "Shape: (82, 8)\n",
      "\n",
      "Columns:\n",
      "Index(['Scheme Code', 'Scheme Name', 'ISIN Div Payout/ISIN Growth',\n",
      "       'ISIN Div Reinvestment', 'Net Asset Value', 'Repurchase Price',\n",
      "       'Sale Price', 'Date'],\n",
      "      dtype='str')\n",
      "\n",
      "Missing Values:\n",
      "Scheme Code                     0\n",
      "Scheme Name                     0\n",
      "ISIN Div Payout/ISIN Growth    39\n",
      "ISIN Div Reinvestment          47\n",
      "Net Asset Value                 0\n",
      "Repurchase Price                0\n",
      "Sale Price                      0\n",
      "Date                            0\n",
      "dtype: int64\n",
      "\n",
      "Duplicates:\n",
      "0\n",
      "\n",
      "==================================================\n",
      "File: data_2006_04_02.csv\n",
      "Shape: (404, 8)\n",
      "\n",
      "Columns:\n",
      "Index(['Scheme Code', 'Scheme Name', 'ISIN Div Payout/ISIN Growth',\n",
      "       'ISIN Div Reinvestment', 'Net Asset Value', 'Repurchase Price',\n",
      "       'Sale Price', 'Date'],\n",
      "      dtype='str')\n",
      "\n",
      "Missing Values:\n",
      "Scheme Code                      0\n",
      "Scheme Name                      0\n",
      "ISIN Div Payout/ISIN Growth    188\n",
      "ISIN Div Reinvestment          272\n",
      "Net Asset Value                  2\n",
      "Repurchase Price                 2\n",
      "Sale Price                       2\n",
      "Date                             0\n",
      "dtype: int64\n",
      "\n",
      "Duplicates:\n",
      "0\n",
      "\n",
      "==================================================\n",
      "File: data_2006_04_03.csv\n",
      "Shape: (1794, 8)\n",
      "\n",
      "Columns:\n",
      "Index(['Scheme Code', 'Scheme Name', 'ISIN Div Payout/ISIN Growth',\n",
      "       'ISIN Div Reinvestment', 'Net Asset Value', 'Repurchase Price',\n",
      "       'Sale Price', 'Date'],\n",
      "      dtype='str')\n",
      "\n",
      "Missing Values:\n",
      "Scheme Code                       0\n",
      "Scheme Name                       0\n",
      "ISIN Div Payout/ISIN Growth     777\n",
      "ISIN Div Reinvestment          1233\n",
      "Net Asset Value                  11\n",
      "Repurchase Price                 10\n",
      "Sale Price                       10\n",
      "Date                              0\n",
      "dtype: int64\n",
      "\n",
      "Duplicates:\n",
      "0\n",
      "\n",
      "==================================================\n",
      "File: data_2006_04_04.csv\n",
      "Shape: (1799, 8)\n",
      "\n",
      "Columns:\n",
      "Index(['Scheme Code', 'Scheme Name', 'ISIN Div Payout/ISIN Growth',\n",
      "       'ISIN Div Reinvestment', 'Net Asset Value', 'Repurchase Price',\n",
      "       'Sale Price', 'Date'],\n",
      "      dtype='str')\n",
      "\n",
      "Missing Values:\n",
      "Scheme Code                       0\n",
      "Scheme Name                       0\n",
      "ISIN Div Payout/ISIN Growth     782\n",
      "ISIN Div Reinvestment          1238\n",
      "Net Asset Value                  11\n",
      "Repurchase Price                 10\n",
      "Sale Price                       10\n",
      "Date                              0\n",
      "dtype: int64\n",
      "\n",
      "Duplicates:\n",
      "0\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "folder = \"DailyNAV\"\n",
    "\n",
    "csv_files = [f for f in os.listdir(folder) if f.endswith(\".csv\")]\n",
    "\n",
    "print(\"Total CSV Files:\", len(csv_files))\n",
    "\n",
    "for file in csv_files[:5]:\n",
    "    print(\"\\n\" + \"=\"*50)\n",
    "    print(\"File:\", file)\n",
    "\n",
    "    df = pd.read_csv(os.path.join(folder, file))\n",
    "\n",
    "    print(\"Shape:\", df.shape)\n",
    "\n",
    "    print(\"\\nColumns:\")\n",
    "    print(df.columns)\n",
    "\n",
    "    print(\"\\nMissing Values:\")\n",
    "    print(df.isnull().sum())\n",
    "\n",
    "    print(\"\\nDuplicates:\")\n",
    "    print(df.duplicated().sum())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f2b53272-b61e-4b07-8cb0-62be0f679498",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "folder = \"DailyNAV\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7eb3ced-b7b1-4f0f-9f2c-c0f4cc868af3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
